name: Deploy My Application

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Environment Variable
      run: echo "API_KEY=${{vars.API_KEY }}" >> $GITHUB_ENV

  
