on:
  workflow_dispatch:

jobs:
  display-secret:
    name: Display Secret Variable
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Secret Variable
        run: |
          echo "La variable secreta es: ${{ secrets.VAR_SECRETA }}"


  
